# Generated by Django 6.0.1 on 2026-02-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_workconfig_wdays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workconfig',
            old_name='break_end',
            new_name='lunch_end',
        ),
        migrations.RenameField(
            model_name='workconfig',
            old_name='break_start',
            new_name='lunch_start',
        ),
    ]
