# Generated by Django 6.0.1 on 2026-02-04 09:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_rename_break_end_workconfig_lunch_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workconfig',
            options={'verbose_name': 'Working Program', 'verbose_name_plural': 'Working Programs'},
        ),
        migrations.AlterField(
            model_name='workconfig',
            name='wdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=14, verbose_name='Working Days'),
        ),
    ]
