# Generated by Django 6.0.1 on 2026-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
