# Generated by Django 6.0.1 on 2026-02-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
