# Generated by Django 6.0.1 on 2026-02-02 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. (+32 470 123 456) or (0032 470 123 456)', regex='^(?:\\+[1-9]\\d{7,14}|00[1-9]\\d{7,14})$')]),
        ),
    ]
