# Generated by Django 6.0.1 on 2026-02-04 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Email is not valid.'}, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be (+32 470 123 456) or (0032 470 123 456)', regex='^(?:\\+[1-9]\\d{7,14}|00[1-9]\\d{7,14})$')]),
        ),
    ]
