# Generated by Django 6.0.1 on 2026-02-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('program', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.workconfig'),
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(related_name='employees', to='services.service'),
        ),
    ]
