# Generated by Django 6.0.1 on 2026-02-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('price', models.FloatField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('CANC', 'Cancelled'), ('DECL', 'Declined'), ('COMP', 'Completed'), ('NOSH', 'Not Showed')], db_index=True, default='PEND', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
            ],
        ),
    ]
