# Generated by Django 6.0.1 on 2026-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('clients', '0002_initial'),
        ('employees', '0003_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee', 'date'], name='appt_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee', 'date', 'start'], name='appt_emp_date_start_idx'),
        ),
    ]
